# Generated by Django 3.2.16 on 2022-11-13 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipes', to='recipe.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Instructions', to='recipe.instruction'),
        ),
    ]
